document.body.style.fontFamily = 'Suranna';
document.body.style.fontWeight = '600';
document.body.style.fontSize = '20px';
var next = document.createElement('button');
var previous = document.createElement('button');
document.body.appendChild(previous);
document.body.appendChild(next);
previous.id = 'Prev';
next.id = 'Nex';
next.style.height = '20px';
next.style.marginLeft = '380px';
next.innerHTML = '>';
next.style.border = 'none';
next.style.background = 'none';
next.style.outline = 'none';
next.style.fontSize = '40px';
previous.style.height = '20px';
previous.innerHTML = '<';
previous.style.border = 'none';
previous.style.background = 'none';
previous.style.outline = 'none';
previous.style.fontSize = '40px';
var content = document.createElement('div');
document.body.appendChild(content);
content.className = "content";

function DaysNames() {
    var NamesWrapper = document.createElement('div');
    content.appendChild(NamesWrapper);
    NamesWrapper.style.display = 'flex';
    NamesWrapper.style.maxHeight = '30px';
    NamesWrapper.style.position = 'absolute';
    NamesWrapper.style.marginTop = '10px';
    NamesWrapper.style.fontSize = '25px';
    var mon = document.createElement('p');
    NamesWrapper.appendChild(mon);
    mon.innerHTML = "Mon";
    mon.style.marginLeft = '10px';
    mon.style.marginRight = '20px';
    var tue = document.createElement('p');
    NamesWrapper.appendChild(tue);
    tue.innerHTML = "Tue ";
    tue.style.marginRight = '22px';
    var wed = document.createElement('p');
    NamesWrapper.appendChild(wed);
    wed.innerHTML = "Wed ";
    wed.style.marginRight = '20px';
    var thu = document.createElement('p');
    NamesWrapper.appendChild(thu);
    thu.innerHTML = "Thu ";
    thu.style.marginRight = '30px';
    var fri = document.createElement('p');
    NamesWrapper.appendChild(fri);
    fri.innerHTML = "Fri ";
    fri.style.marginRight = '35px';
    var sat = document.createElement('p');
    NamesWrapper.appendChild(sat);
    sat.innerHTML = "Sat ";
    sat.style.marginRight = '30px';
    var sun = document.createElement('p');
    NamesWrapper.appendChild(sun);
    sun.innerHTML = "Sun ";
    sun.style.color = '#16ACE3';
}
content.style.display = 'flex';
var CalendarPage = document.createElement('table');
CalendarPage.className = 'CalendarPage';
content.appendChild(CalendarPage);